# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://nucleo.jor.br/ #
baseurl: #
title: Núcleo Jornalismo
email: nucleo@voltdata.info
author: Núcleo Jornalismo
description: > # "Write an awesome description for your new site here.
  Análises e investigações sobre o impacto das redes sociais na sociedade
copyright: '<img src="{{site.baseurl}}/img/landing-nucleo_logo+tagline.png" width="200px" />'
credits: 'Copyright © 2021 | Volt Data Lab. Todos os direitos reservados. Reprodução integral do conteúdo deste site depende de aprovação, mas citações e reprodução parcial, com links para origem, são permitidas e apreciadas. Este site utiliza Google Analytics.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: /:categories/:year-:month-:day-:title
plugins:
  - jekyll-paginate
  - jekyll-feed

paginate:           20
paginate_path:      "/arquivo/p:num/"

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/nucleojor
  - title: facebook
    url: https://www.facebook.com/Nucleojor-103656567831757
  - title: github
    url: https://github.com/voltdatalab
  - title: instagram
    url: https://www.instagram.com/nucleojornalismo/
  - title: linkedin
    url: https://www.linkedin.com/company/71866321
  - title: whatsapp
    url: https://wa.me/5511934441844
  - title: telegram
    url: https://t.me/nucleojor


collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
